'use client'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { SynthesizeResponse, Source } from '@/lib/api'
import { renderContent, buildSourceMap, E4C_SOURCE_ID } from '@/lib/renderContent'
import Navbar from '@/components/Navbar'
import SourceDrawer from '@/components/SourceDrawer'

const R = { fontFamily: 'Roboto, system-ui, sans-serif' }

// Fixed metadata for the E4C knowledge base source
const E4C_SOURCE: Source = {
  id:          E4C_SOURCE_ID,
  title:       'Engineering For Change Knowledge Base',
  excerpt:     'Content retrieved from E4C\'s Solutions Library, Research Reports, and News & Insights via KnowledgeXpert.',
  url:         'https://www.engineeringforchange.org',
  source_type: 'e4c',
}

export default function BriefPage() {
  const router = useRouter()
  const [data,          setData]          = useState<SynthesizeResponse | null>(null)
  const [activeSource,  setActiveSource]  = useState<Source | null>(null)
  const [drawerOpen,    setDrawerOpen]    = useState(false)
  const [highlightedId, setHighlightedId] = useState<string | null>(null)
  const [copied,        setCopied]        = useState(false)

  useEffect(() => {
    const raw = sessionStorage.getItem('brief_result')
    if (!raw) { router.push('/'); return }
    setData(JSON.parse(raw))
  }, [router])

  // No useCallback — plain function so it always reads current `data`
  function handleCiteClick(id: string) {
    if (!data) return
    if (id === E4C_SOURCE_ID) {
      setActiveSource(E4C_SOURCE)
    } else {
      setActiveSource(data.sources.find(s => s.id === id) ?? null)
    }
    setHighlightedId(id)
    setDrawerOpen(true)
  }

  function closeDrawer() {
    setDrawerOpen(false)
    setHighlightedId(null)
  }

  async function handleCopyMarkdown() {
    if (!data?.brief) return
    const { brief } = data
    const md = [
      `# ${brief.title}`, '',
      '## Executive Summary', brief.executive_summary, '',
      ...brief.sections.flatMap(s => [`## ${s.heading}`, s.content, '']),
      '## Key Findings', ...brief.key_findings.map(f => `- ${f}`), '',
      '## Limitations', brief.limitations, '',
      '---',
      '*Generated by E4C Insights · Sources: E4C Knowledge Base, World Bank Open Data, WHO GHO*',
    ].join('\n')
    await navigator.clipboard.writeText(md)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  if (!data?.brief) return (
    <>
      <Navbar />
      <main style={{ minHeight: '60vh', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        <p style={{ ...R, color: '#9ab0bc' }}>Loading…</p>
      </main>
    </>
  )

  const { brief, sources, flag_for_review } = data
  const sourceMap = buildSourceMap(
    sources.map((s: Source) => ({ id: s.id, title: s.title, excerpt: s.excerpt, url: s.url }))
  )
  const renderOpts = { sources: sourceMap, onCiteClick: handleCiteClick, highlightedId }

  return (
    <>
      <Navbar />
      <SourceDrawer source={activeSource} isOpen={drawerOpen} onClose={closeDrawer} />

      <main style={{ transition: 'margin-right 0.28s', marginRight: drawerOpen ? '360px' : '0' }}>

        {/* Brief header */}
        <div style={{ background: 'linear-gradient(135deg, #1a3a4a, #00557b)', padding: '32px 24px', borderBottom: '4px solid #5cb1d0' }} className="no-print">
          <div style={{ maxWidth: '760px', margin: '0 auto' }}>
            <p style={{ ...R, fontWeight: 700, fontSize: '11px', letterSpacing: '0.12em', textTransform: 'uppercase', color: '#5cb1d0', marginBottom: '10px' }}>
              Policy Brief
              {flag_for_review.length > 0 && (
                <span style={{ marginLeft: '12px', background: '#e6a817', color: '#1a2a34', padding: '2px 8px', fontSize: '10px' }}>
                  {flag_for_review.length} SECTION{flag_for_review.length > 1 ? 'S' : ''} FLAGGED
                </span>
              )}
            </p>
            <h1 style={{ ...R, fontWeight: 700, fontSize: '32px', lineHeight: '42px', color: 'white', marginBottom: '8px' }}>{brief.title}</h1>
            <p style={{ ...R, fontSize: '14px', color: '#5cb1d0', marginBottom: '20px' }}>
              {data.topic} · {data.region} · {sources.length} sources cited
            </p>
            <div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap' }}>
              {[
                { label: 'Print / Save PDF', action: () => window.print() },
                { label: copied ? '✓ Copied' : 'Copy Markdown', action: handleCopyMarkdown },
                { label: '← New Brief', action: () => router.push('/') },
              ].map(btn => (
                <button key={btn.label} onClick={btn.action}
                  style={{ ...R, fontWeight: 700, fontSize: '11px', letterSpacing: '0.08em', textTransform: 'uppercase', padding: '8px 16px', border: '2px dotted white', background: 'transparent', color: 'white', cursor: 'pointer' }}>
                  {btn.label}
                </button>
              ))}
            </div>
          </div>
        </div>

        <article style={{ maxWidth: '760px', margin: '0 auto', padding: '40px 24px' }}>

          {/* Executive summary */}
          <section style={{ background: '#e8f5fb', borderLeft: '5px solid #00557b', padding: '20px 24px', marginBottom: '28px' }}>
            <p style={{ ...R, fontWeight: 700, fontSize: '11px', letterSpacing: '0.1em', textTransform: 'uppercase', color: '#00557b', marginBottom: '12px' }}>Executive Summary</p>
            <p style={{ ...R, fontSize: '15px', lineHeight: 1.8, color: '#1a2a34' }}>
              {renderContent(brief.executive_summary, renderOpts)}
            </p>
          </section>

          {/* Key findings */}
          <section style={{ background: 'white', border: '1px solid #e8eef1', padding: '20px 24px', marginBottom: '20px' }}>
            <p style={{ ...R, fontWeight: 700, fontSize: '11px', letterSpacing: '0.1em', textTransform: 'uppercase', color: '#5a7280', marginBottom: '16px' }}>Key Findings</p>
            <ul style={{ listStyle: 'none', padding: 0 }}>
              {brief.key_findings.map((f, i) => (
                <li key={i} style={{ display: 'flex', gap: '12px', marginBottom: '12px', alignItems: 'flex-start' }}>
                  <div style={{ width: '6px', height: '6px', background: '#00557b', flexShrink: 0, marginTop: '8px' }} />
                  <span style={{ ...R, fontSize: '14px', lineHeight: 1.7, color: '#1a2a34' }}>
                    {renderContent(f, renderOpts)}
                  </span>
                </li>
              ))}
            </ul>
          </section>

          {/* Data highlights */}
          {brief.data_highlights.length > 0 && (
            <section style={{ marginBottom: '20px' }}>
              <p style={{ ...R, fontWeight: 700, fontSize: '11px', letterSpacing: '0.1em', textTransform: 'uppercase', color: '#5a7280', marginBottom: '12px' }}>Data at a Glance</p>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(180px, 1fr))', gap: '10px' }}>
                {brief.data_highlights.map((d, i) => (
                  <button key={i} onClick={() => handleCiteClick(d.src_id)}
                    style={{ background: 'white', border: '1px solid #e8eef1', padding: '16px', textAlign: 'left', cursor: 'pointer' }}
                    onMouseEnter={e => (e.currentTarget.style.borderColor = '#5cb1d0')}
                    onMouseLeave={e => (e.currentTarget.style.borderColor = '#e8eef1')}>
                    <p style={{ ...R, fontWeight: 700, fontSize: '16px', color: '#00557b', lineHeight: 1.3, marginBottom: '4px' }}>
                      {d.stat.includes(':') ? d.stat.split(':').slice(1).join(':').trim() : d.stat}
                    </p>
                    <p style={{ ...R, fontSize: '11px', color: '#9ab0bc' }}>
                      {d.stat.includes(':') ? d.stat.split(':')[0] : ''}
                    </p>
                    <p style={{ ...R, fontSize: '10px', color: '#5cb1d0', marginTop: '4px' }}>{d.source_name}</p>
                  </button>
                ))}
              </div>
            </section>
          )}

          {/* Sections */}
          {brief.sections.map(section => {
            const isFlagged = flag_for_review.includes(section.heading)
            return (
              <section key={section.heading} style={{ background: 'white', border: `1px solid ${isFlagged ? '#f0d090' : '#e8eef1'}`, marginBottom: '16px', overflow: 'hidden' }}>
                <div style={{ padding: '14px 20px', borderBottom: `1px solid ${isFlagged ? '#f0d090' : '#e8eef1'}`, background: isFlagged ? '#fffbf0' : '#f5f7f8', display: 'flex', alignItems: 'center', gap: '8px' }}>
                  {isFlagged && <span style={{ color: '#e6a817' }}>⚠</span>}
                  <h2 style={{ ...R, fontWeight: 700, fontSize: '15px', color: '#00557b' }}>{section.heading}</h2>
                </div>
                <div style={{ padding: '20px' }}>
                  {section.content.split(/\n\n+/).map((para, i) => (
                    <p key={i} style={{ ...R, fontSize: '14px', lineHeight: 1.8, color: '#3a5060', marginBottom: '12px' }}>
                      {renderContent(para, renderOpts)}
                    </p>
                  ))}
                </div>
              </section>
            )
          })}

          {/* Assumptions & Limitations */}
          {(brief.assumptions.length > 0 || brief.limitations) && (
            <section style={{ background: 'white', border: '1px solid #e8eef1', padding: '20px', marginBottom: '16px' }}>
              {brief.assumptions.length > 0 && (
                <div style={{ marginBottom: '16px' }}>
                  <p style={{ ...R, fontWeight: 700, fontSize: '11px', letterSpacing: '0.1em', textTransform: 'uppercase', color: '#e6a817', marginBottom: '10px' }}>Assumptions</p>
                  {brief.assumptions.map((a, i) => (
                    <p key={i} style={{ ...R, fontSize: '13px', color: '#7a5010', marginBottom: '6px' }}>⚠ {a}</p>
                  ))}
                </div>
              )}
              {brief.limitations && (
                <div style={{ borderTop: brief.assumptions.length > 0 ? '1px solid #e8eef1' : 'none', paddingTop: brief.assumptions.length > 0 ? '16px' : '0' }}>
                  <p style={{ ...R, fontWeight: 700, fontSize: '11px', letterSpacing: '0.1em', textTransform: 'uppercase', color: '#5a7280', marginBottom: '8px' }}>Limitations</p>
                  <p style={{ ...R, fontSize: '13px', color: '#5a7280', lineHeight: 1.6 }}>{brief.limitations}</p>
                </div>
              )}
            </section>
          )}

          {/* References */}
          <section style={{ background: 'white', border: '1px solid #e8eef1', padding: '20px', marginBottom: '16px' }}>
            <p style={{ ...R, fontWeight: 700, fontSize: '11px', letterSpacing: '0.1em', textTransform: 'uppercase', color: '#5a7280', marginBottom: '16px' }}>References ({sources.length + 1})</p>

            {/* E4C as first reference */}
            <div style={{ display: 'flex', gap: '12px', marginBottom: '12px' }}>
              <span style={{ fontFamily: 'monospace', fontSize: '10px', color: '#1a5c3a', flexShrink: 0, marginTop: '2px', minWidth: '60px' }}>E4C</span>
              <div>
                <p style={{ ...R, fontWeight: 700, fontSize: '12px', color: '#1a2a34', marginBottom: '2px' }}>Engineering For Change Knowledge Base</p>
                <p style={{ ...R, fontSize: '11px', color: '#9ab0bc', marginBottom: '2px' }}>Solutions Library, Research Reports, and News & Insights via KnowledgeXpert</p>
                <a href="https://www.engineeringforchange.org" target="_blank" rel="noopener" style={{ ...R, fontSize: '10px', color: '#5cb1d0' }}>engineeringforchange.org</a>
              </div>
            </div>

            {sources.map((s: Source) => (
              <div key={s.id} style={{ display: 'flex', gap: '12px', marginBottom: '12px' }}>
                <span style={{ fontFamily: 'monospace', fontSize: '10px', color: '#00557b', flexShrink: 0, marginTop: '2px', minWidth: '60px' }}>{s.id}</span>
                <div>
                  <p style={{ ...R, fontWeight: 700, fontSize: '12px', color: '#1a2a34', marginBottom: '2px' }}>{s.title}</p>
                  {s.excerpt && <p style={{ ...R, fontSize: '11px', color: '#9ab0bc', marginBottom: '2px' }}>{s.excerpt}</p>}
                  {s.url && <a href={s.url} target="_blank" rel="noopener" style={{ ...R, fontSize: '10px', color: '#5cb1d0' }}>{s.url}</a>}
                </div>
              </div>
            ))}
          </section>

          {/* Footer */}
          <footer style={{ borderTop: '2px solid #e8eef1', paddingTop: '20px', paddingBottom: '40px' }}>
            <p style={{ ...R, fontSize: '11px', color: '#9ab0bc', lineHeight: 1.7 }}>
              Generated using the E4C Insights pipeline: knowledge retrieved from Engineering For Change&apos;s
              knowledge base via KnowledgeXpert (Bear Creek AI), quantitative data from World Bank Open Data
              and WHO Global Health Observatory, synthesised using gpt-5.4. All sections reviewed by a human
              before publication. No causal claims or policy prescriptions are made by this system.
              Generated {new Date().toLocaleDateString('en-GB', { year: 'numeric', month: 'long', day: 'numeric' })}.
            </p>
          </footer>
        </article>
      </main>
    </>
  )
}